---
title: "Chapter 4"
author: "Jake Rozran"
date: "5/20/2021"
output: html_document
---

# 4.1

```{r chp4.1}
library(fpp3)

tourism %>%
    features(Trips, list(mean = mean)) %>%
    arrange(mean)

tourism %>% 
    features(Trips, quantile)
```

# 4.2

```{r chp4.2}
tourism %>% 
    features(Trips, feat_acf)

```

# 4.3

```{r chp4.3}
tourism %>%
  features(Trips, feat_stl)

tourism %>%
  features(Trips, feat_stl) %>%
  ggplot(aes(x = trend_strength, y = seasonal_strength_year,
             col = Purpose)) +
  geom_point() +
  facet_wrap(vars(State))

tourism %>%
  features(Trips, feat_stl) %>%
  filter(
    seasonal_strength_year == max(seasonal_strength_year)
  ) %>%
  left_join(tourism, by = c("State", "Region", "Purpose")) %>%
  ggplot(aes(x = Quarter, y = Trips)) +
  geom_line() +
  facet_grid(vars(State, Region, Purpose))
```

# 4.5

```{r chp 4.5}
library(broom)
library(glue)

tourism_features <- tourism %>%
    features(Trips, feature_set(pkgs = "feasts"))

pcs <- tourism_features %>%
    select(-State, -Region, -Purpose) %>%
    prcomp(scale = TRUE) %>%
    augment(tourism_features)

pcs %>%
    ggplot(aes(x = .fittedPC1, y = .fittedPC2, col = Purpose)) +
    geom_point() +
    theme(aspect.ratio = 1)

outliers <- pcs %>%
  filter(.fittedPC1 > 10) %>%
  select(Region, State, Purpose, .fittedPC1, .fittedPC2)

outliers

outliers %>%
    left_join(tourism, by = c("State", "Region", "Purpose")) %>%
    mutate(Series = glue("{State}", "{Region}", "{Purpose}", .sep = "\n\n")) %>%
    ggplot(aes(x = Quarter, y = Trips)) +
    geom_line() +
    facet_grid(Series ~ ., scales = "free") +
    labs(title = "Outlying time series in PC space")
```