---
title: "Chapter 5"
author: "Jake Rozran"
date: "5/24/2021"
output: html_document
---

# 5.1

```{r chp5.1}
library(fpp3)

gdppc <- global_economy %>%
    mutate(GDP_per_capita = GDP / Population)

# ggplot(gdppc, aes(x = Year, y = GDP_per_capita, group = Country, color = Country)) +
#   geom_line()

gdppc %>%
  filter(Country == "Sweden") %>%
  autoplot(GDP_per_capita) +
  labs(y = "$US", title = "GDP per capita for Sweden")

fit <- gdppc %>%
  model(trend_model = TSLM(GDP_per_capita ~ trend()))

fit

fit %>% forecast(h = "3 years")

fit %>%
    forecast(h = "3 years") %>%
    filter(Country == "Sweden") %>%
    autoplot(gdppc) +
    labs(y = "$US", title = "GDP per capita for Sweden")
```

# 5.2

```{r chp5.2}
bricks <- aus_production %>%
    filter_index("1970 Q1" ~ "2004 Q4")

bricks %>% 
    model(MEAN(Bricks)) %>% 
    forecast(h = "3 years") %>%
    autoplot(bricks) %>% 
    labs(y = "Bricks", x = "Quarter", title = "Average method")

bricks %>% 
    model(NAIVE(Bricks)) %>% 
    forecast(h = "3 years") %>%
    autoplot(bricks) %>% 
    labs(y = "Bricks", x = "Quarter", title = "Naive method")

bricks %>% 
    model(SNAIVE(Bricks ~ lag("year"))) %>% 
    forecast(h = "6 years") %>%
    autoplot(bricks) %>% 
    labs(y = "Bricks", x = "Quarter", title = "Seasonal Naive method")

bricks %>% 
    model(RW(Bricks ~ drift())) %>% 
    forecast(h = "6 years") %>%
    autoplot(bricks) %>% 
    labs(y = "Bricks", x = "Quarter", title = "Drift method")

# Set training data from 1992 to 2006
train <- aus_production %>%
    filter_index("1992 Q1" ~ "2006 Q4")

# Fit the models
beer_fit <- train %>%
    model(
        Mean = MEAN(Beer),
        `Naïve` = NAIVE(Beer),
        `Seasonal naïve` = SNAIVE(Beer)
    )

# Generate forecasts for 14 quarters
beer_fc <- beer_fit %>% 
    forecast(h = 14)

# Plot forecasts against actual values
beer_fc %>%
    autoplot(train, level = NULL) +
    autolayer(
        filter_index(aus_production, "2007 Q1" ~ .),
        colour = "black"
    ) +
    labs(
        y = "Megalitres",
        title = "Forecasts for quarterly beer production"
    ) +
    guides(colour = guide_legend(title = "Forecast"))

# Re-index based on trading days
google_stock <- gafa_stock %>%
    filter(Symbol == "GOOG", year(Date) >= 2015) %>%
    mutate(day = row_number()) %>%
    update_tsibble(index = day, regular = TRUE)

# Filter the year of interest
google_2015 <- google_stock %>% 
    filter(year(Date) == 2015)

# Fit the models
google_fit <- google_2015 %>%
    model(
        Mean = MEAN(Close),
        `Naïve` = NAIVE(Close),
        Drift = NAIVE(Close ~ drift())
    )

# Produce forecasts for the trading days in January 2016
google_jan_2016 <- google_stock %>%
    filter(yearmonth(Date) == yearmonth("2016 Jan"))

google_fc <- google_fit %>%
    forecast(new_data = google_jan_2016)

# Plot the forecasts
google_fc %>%
    autoplot(google_2015, level = NULL) +
    autolayer(google_jan_2016, Close, colour = "black") +
    labs(y = "$US",
         title = "Google daily closing stock prices",
         subtitle = "(Jan 2015 - Jan 2016)") +
    guides(colour = guide_legend(title = "Forecast"))
```

# 5.3

```{r chp5.3}
augment(beer_fit)
```

# 5.4

```{r chp5.4}
autoplot(google_2015, Close) +
    labs(y = "$US",
         title = "Google daily closing stock prices in 2015")

aug <- google_2015 %>%
    model(NAIVE(Close)) %>%
    augment()

autoplot(aug, .innov) +
    labs(y = "$US",
         title = "Residuals from the Naïve method")

aug %>%
    ggplot(aes(x = .innov)) +
    geom_histogram() +
    labs(title = "Histogram of residuals")

aug %>%
    ACF(.innov) %>%
    autoplot() +
    labs(title = "Residuals from the Naïve method")

google_2015 %>%
    model(NAIVE(Close)) %>%
    gg_tsresiduals()
```

# 5.5

```{r chp5.5}
fit <- google_2015 %>%
    model(NAIVE(Close))

sim <- fit %>% 
  generate(h = 30, times = 10000, bootstrap = TRUE)

sim

google_2015 %>%
    ggplot(aes(x = day)) +
    geom_line(aes(y = Close)) +
    geom_line(aes(y = .sim), alpha = 0.2, color = "black",
              data = sim) +
    labs(title="Google daily closing stock price", y="$US" ) +
    guides(col = FALSE)

fc <- fit %>% 
    forecast(h = 30, bootstrap = TRUE)

fc

autoplot(fc, google_2015) +
    labs(title="Google daily closing stock price", y="$US" )

google_2015 %>%
  model(NAIVE(Close)) %>%
  forecast(h = 10, bootstrap = TRUE, times = 10000) %>%
  hilo()
```

# 5.6

```{r chp5.6}
prices %>%
    filter(!is.na(eggs)) %>%
    model(RW(log(eggs) ~ drift())) %>%
    forecast(h = 50) %>%
    autoplot(prices %>% filter(!is.na(eggs)),
             level = 80, point_forecast = lst(mean, median)) +
    labs(title = "Annual egg prices",
         y = "$US (in cents adjusted for inflation) ")
```